// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5UqTV3bj62J_8CrUf_MSLpgaBr4f01tE',
    appId: '1:861717205433:web:cb3c5c24210dee6813e668',
    messagingSenderId: '861717205433',
    projectId: 'gagga-7164a',
    authDomain: 'gagga-7164a.firebaseapp.com',
    databaseURL: 'https://gagga-7164a-default-rtdb.firebaseio.com',
    storageBucket: 'gagga-7164a.appspot.com',
    measurementId: 'G-XF5C7G06WV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACsFGn3TBgfphN_AEqREWoEUoRDNlsxcU',
    appId: '1:861717205433:android:81d825c561c82ed213e668',
    messagingSenderId: '861717205433',
    projectId: 'gagga-7164a',
    databaseURL: 'https://gagga-7164a-default-rtdb.firebaseio.com',
    storageBucket: 'gagga-7164a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRe-SjPpASHmyO1tPDhycbxY6FJ_jgFTs',
    appId: '1:861717205433:ios:3d116a1da6d9de8913e668',
    messagingSenderId: '861717205433',
    projectId: 'gagga-7164a',
    databaseURL: 'https://gagga-7164a-default-rtdb.firebaseio.com',
    storageBucket: 'gagga-7164a.appspot.com',
    iosBundleId: 'com.mycompany.gagga',
  );
}
